name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
        versionSpec: '5.x'

    - name: Use GitVersion to generate version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.10

    - name: Restore dependencies
      run: dotnet restore src/ContainerTagRemover/ContainerTagRemover.sln

    - name: Build solution
      run: dotnet build src/ContainerTagRemover/ContainerTagRemover.sln --no-restore /p:Version=${{ steps.gitversion.outputs.FullSemVer }}

    - name: Run tests
      run: dotnet test src/ContainerTagRemover/ContainerTagRemover.sln --no-build --verbosity normal

    - name: Package tool
      run: dotnet pack src/ContainerTagRemover/ContainerTagRemover.csproj --output ./nupkg /p:Version=${{ steps.gitversion.outputs.FullSemVer }}

    - name: Publish tool
      if: github.event_name != 'pull_request'
      run: dotnet nuget push ./nupkg/*.nupkg  -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Create GitHub release
      if: github.event_name != 'pull_request'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.FullSemVer }}
        release_name: Release ${{ steps.gitversion.outputs.FullSemVer }}
        body: |
          Release notes for ${{ steps.gitversion.outputs.FullSemVer }}
