name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool

    - name: Use GitVersion to generate version
      run: dotnet-gitversion /output json /showvariable FullSemVer

    - name: Restore dependencies
      run: dotnet restore src/ContainerTagRemover/ContainerTagRemover.sln

    - name: Build solution
      run: dotnet build src/ContainerTagRemover/ContainerTagRemover.sln --no-restore

    - name: Run tests
      run: dotnet test src/ContainerTagRemover/ContainerTagRemover.sln --no-build --verbosity normal

    - name: Package tool
      run: dotnet pack src/ContainerTagRemover/ContainerTagRemover.csproj --output ./nupkg

    - name: Publish .nupkg as artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./nupkg/*.nupkg

    - name: Publish tool
      if: github.event_name != 'pull_request'
      run: dotnet nuget push ./nupkg/*.nupkg --source nuget.org --api-key ${{ secrets.NUGET_API_KEY }}

    - name: Create GitHub release
      if: github.event_name != 'pull_request'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.FullSemVer }}
        release_name: Release ${{ steps.gitversion.outputs.FullSemVer }}
        draft: false
        prerelease: false
